import type { ShowDefinition } from "./types";

export const SHOW_TAGS: Record<string, ShowDefinition> = {
  "real-housewives-beverly-hills": {
    tag: "real-housewives-beverly-hills",
    label: "RHOBH",
    fullName: "The Real Housewives of Beverly Hills",
    keywords: [
      "rhobh", "beverly hills", "kyle richards", "dorit kemsley",
      "erika jayne", "garcelle beauvais", "sutton stracke", "crystal minkoff",
    ],
    color: "#C4A265",
    intro: "The Real Housewives of Beverly Hills follows the glamorous and dramatic lives of women living in one of the most exclusive zip codes in the world. From designer feuds to explosive dinner parties in international destinations, RHOBH has delivered some of Bravo's most iconic moments since its premiere in 2010. Season 15 is currently airing with Kyle Richards, Erika Jayne, Dorit Kemsley, Sutton Stracke, and newcomers Bozoma Saint John, Rachel Zoe, and Amanda Frances shaking up the diamond holders.",
    currentSeason: 15,
    airDay: "Wednesdays at 8PM ET",
    network: "Bravo",
    status: "airing",
  },
  "real-housewives-atlanta": {
    tag: "real-housewives-atlanta",
    label: "RHOA",
    fullName: "The Real Housewives of Atlanta",
    keywords: [
      "rhoa", "real housewives of atlanta", "kandi burruss", "kenya moore",
      "drew sidora", "sheree whitfield",
    ],
    color: "#E84393",
    intro: "The Real Housewives of Atlanta is Bravo's crown jewel and the franchise that redefined what reality TV could be. Known for legendary one-liners, unforgettable reunions, and more shade than a Georgia peach tree, RHOA has been a cultural force since 2008. Season 17 premieres April 5th with a stacked cast including Porsha Williams, Phaedra Parks, and explosive newcomers Pinky Cole and K. Michelle.",
    currentSeason: 17,
    airDay: "Sundays at 8PM ET",
    network: "Bravo",
    status: "upcoming",
  },
  "real-housewives-new-jersey": {
    tag: "real-housewives-new-jersey",
    label: "RHONJ",
    fullName: "The Real Housewives of New Jersey",
    keywords: [
      "rhonj", "real housewives of new jersey", "teresa giudice",
      "melissa gorga", "margaret josephs",
    ],
    color: "#00B894",
    intro: "The Real Housewives of New Jersey is where family drama meets reality TV at its rawest. From Teresa Giudice's table flip to the Gorga family saga that has spanned over a decade, RHONJ blurs the line between entertainment and genuine family conflict in ways no other franchise can. The show is currently between seasons with major cast changes reported for the next installment.",
    currentSeason: 14,
    airDay: null,
    network: "Bravo",
    status: "between-seasons",
  },
  "real-housewives-new-york": {
    tag: "real-housewives-new-york",
    label: "RHONY",
    fullName: "The Real Housewives of New York City",
    keywords: [
      "rhony", "real housewives of new york", "brynn whitfield",
      "jenna lyons", "sai de silva", "ubah hassan", "erin lichy",
      "jessel taank",
    ],
    color: "#0984E3",
    intro: "The Real Housewives of New York City brought Manhattan socialite culture to Bravo audiences and gave the world Bethenny Frankel, the Countess, and more memorable moments than any franchise outside Atlanta. After a full cast reboot in Season 14, RHONY is finding its footing with a fresh group of New York women navigating careers, relationships, and the relentless pace of the city.",
    currentSeason: 15,
    airDay: null,
    network: "Bravo",
    status: "between-seasons",
  },
  "real-housewives-salt-lake-city": {
    tag: "real-housewives-salt-lake-city",
    label: "RHOSLC",
    fullName: "The Real Housewives of Salt Lake City",
    keywords: [
      "rhoslc", "salt lake city", "lisa barlow", "heather gay",
      "meredith marks", "mary cosby",
    ],
    color: "#A29BFE",
    intro: "The Real Housewives of Salt Lake City exploded onto the scene as Bravo's most unpredictable franchise. Between federal arrests filmed on camera, cult-adjacent accusations, and some of the most genuinely unhinged cast dynamics in Housewives history, RHOSLC proves that drama knows no geographic boundaries. The show has quickly become a fan favorite for viewers who want their reality TV served with an extra dose of chaos.",
    currentSeason: 5,
    airDay: null,
    network: "Bravo",
    status: "between-seasons",
  },
  "real-housewives-miami": {
    tag: "real-housewives-miami",
    label: "RHOM",
    fullName: "The Real Housewives of Miami",
    keywords: [
      "rhom", "real housewives of miami", "larsa pippen", "alexia nepola",
      "lisa hochstein", "guerdy abraira",
    ],
    color: "#FF7675",
    intro: "The Real Housewives of Miami was canceled, resurrected on Peacock, and came back stronger than ever. The Miami cast brings Latin flair, waterfront glamour, and friendships that run deeper and messier than the Atlantic. With Larsa Pippen, Alexia Nepola, Lisa Hochstein, and Guerdy Abraira leading the charge, RHOM has cemented itself as one of the most entertaining franchises in the Bravo universe.",
    currentSeason: 7,
    airDay: null,
    network: "Bravo/Peacock",
    status: "between-seasons",
  },
  "real-housewives-potomac": {
    tag: "real-housewives-potomac",
    label: "RHOP",
    fullName: "The Real Housewives of Potomac",
    keywords: [
      "rhop", "real housewives of potomac", "gizelle bryant", "karen huger",
      "ashley darby", "candiace dillard",
    ],
    color: "#6C5CE7",
    intro: "The Real Housewives of Potomac is the most consistently excellent franchise that does not get enough credit. The Karen Huger and Gizelle Bryant rivalry is one of the greatest long-running feuds in Bravo history, and the cast delivers compelling drama every single season without fail. Season 10 is currently airing with new cast additions keeping the Potomac ladies on their toes.",
    currentSeason: 10,
    airDay: null,
    network: "Bravo",
    status: "airing",
  },
  "real-housewives-dubai": {
    tag: "real-housewives-dubai",
    label: "RHODubai",
    fullName: "The Real Housewives of Dubai",
    keywords: ["rhodubai", "real housewives of dubai"],
    color: "#FDCB6E",
    intro: "The Real Housewives of Dubai takes the franchise international with a cast living the most opulent lifestyles in the Bravo universe. Gold-plated everything, desert getaways, and cultural clashes between cast members from vastly different backgrounds make RHODubai a unique entry in the Housewives canon. The show continues to find its identity as one of the newer additions to the franchise.",
    currentSeason: 2,
    airDay: null,
    network: "Bravo",
    status: "between-seasons",
  },
  "vanderpump-rules": {
    tag: "vanderpump-rules",
    label: "VPR",
    fullName: "Vanderpump Rules",
    keywords: [
      "vanderpump rules", "vanderpump", "tom sandoval", "ariana madix",
      "tom schwartz", "scheana shay", "lala kent", "katie maloney",
      "james kennedy",
    ],
    color: "#E17055",
    intro: "Vanderpump Rules started as a Real Housewives spinoff and became the show that broke the internet. The Scandoval cheating scandal in 2023 turned VPR into the most talked-about show on television and proved that reality TV, when it captures something genuinely real, is the most powerful storytelling medium on the planet. The show underwent a full cast reboot for Season 12, returning to its roots at SUR with an entirely new group.",
    currentSeason: 12,
    airDay: null,
    network: "Bravo",
    status: "between-seasons",
  },
  "below-deck": {
    tag: "below-deck",
    label: "Below Deck",
    fullName: "Below Deck",
    keywords: [
      "below deck", "captain lee", "captain sandy", "below deck med",
      "below deck sailing", "below deck adventure",
    ],
    color: "#00CEC9",
    intro: "Below Deck and its spinoffs put cameras on luxury yachts and proved that confined spaces plus alcohol plus demanding charter guests equals television gold. Across the original series, Below Deck Mediterranean, Below Deck Down Under, Below Deck Sailing Yacht, and Below Deck Adventure, the franchise has become Bravo's most prolific content engine. Below Deck Down Under Season 4 is currently airing.",
    currentSeason: 4,
    airDay: "Mondays at 8PM ET",
    network: "Bravo",
    status: "airing",
  },
  "summer-house": {
    tag: "summer-house",
    label: "Summer House",
    fullName: "Summer House",
    keywords: [
      "summer house", "kyle cooke", "amanda batula", "carl radke",
      "lindsay hubbard", "paige desorbo", "ciara miller", "west wilson",
    ],
    color: "#55EFC4",
    intro: "Summer House follows a group of friends who share a house in the Hamptons every weekend during the summer, and somehow manage to create more drama per square foot than any other show on television. Season 10 is currently airing and has been completely overshadowed by the off-camera bombshell that Amanda Batula and West Wilson confirmed they are dating, sending the entire Bravoverse into meltdown mode.",
    currentSeason: 10,
    airDay: "Tuesdays at 8PM ET",
    network: "Bravo",
    status: "airing",
  },
  "the-valley": {
    tag: "the-valley",
    label: "The Valley",
    fullName: "The Valley",
    keywords: [
      "the valley", "jax taylor", "brittany cartwright", "kristen doute",
      "luke broderick",
    ],
    color: "#FAB1A0",
    intro: "The Valley is the Vanderpump Rules spinoff that follows Jax Taylor, Brittany Cartwright, Kristen Doute, and their circle of friends as they navigate life in the San Fernando Valley. Season 3 brings Lala Kent and Tom Schwartz into the full-time cast, adding even more VPR alumni to the mix. The show premieres April 1st and promises unresolved tensions and major life changes.",
    currentSeason: 3,
    airDay: "Tuesdays at 9PM ET",
    network: "Bravo",
    status: "airing",
  },
  "southern-charm": {
    tag: "southern-charm",
    label: "Southern Charm",
    fullName: "Southern Charm",
    keywords: [
      "southern charm", "craig conover", "shep rose", "austen kroll",
      "madison lecroy",
    ],
    color: "#FFEAA7",
    intro: "Southern Charm brings Charleston, South Carolina's social elite to Bravo with a mix of old money manners, new money ambitions, and enough romantic entanglements to fill a Southern gothic novel. Craig Conover, Shep Rose, Austen Kroll, and Madison LeCroy have been navigating life, love, and the Charleston bar scene for eleven seasons. The Season 11 reunion just wrapped with nearly every cast member freshly single.",
    currentSeason: 11,
    airDay: "Thursdays at 9PM ET",
    network: "Bravo",
    status: "airing",
  },
  "bachelor-bachelorette": {
    tag: "bachelor-bachelorette",
    label: "Bachelor",
    fullName: "The Bachelor / The Bachelorette",
    keywords: [
      "the bachelor", "bachelorette", "bachelor in paradise",
      "golden bachelor", "rose ceremony", "final rose",
    ],
    color: "#FF3838",
    intro: "The Bachelor and The Bachelorette franchise has been handing out roses since 2002 and shows no signs of slowing down. Between the original series, The Bachelorette, Bachelor in Paradise, and The Golden Bachelor, the franchise covers every demographic of hopeless romantic. Rose ceremonies, dramatic exits, and the eternal question of whether anyone actually finds lasting love on this show keep millions of viewers coming back every season.",
    currentSeason: null,
    airDay: null,
    network: "ABC",
    status: "between-seasons",
  },
  "love-island": {
    tag: "love-island",
    label: "Love Island",
    fullName: "Love Island",
    keywords: ["love island", "love island usa", "love island uk"],
    color: "#FF9FF3",
    intro: "Love Island drops a group of attractive singles into a villa with one goal: couple up or get dumped. Both the UK and USA versions have massive followings, with the US version finally hitting its stride around Season 5 and delivering the kind of chaotic, emotional, and wildly entertaining content that the UK original has been producing for years. If you want your reality TV served with sun, swimwear, and terrible romantic decisions, this is your show.",
    currentSeason: null,
    airDay: null,
    network: "Peacock/ITV2",
    status: "between-seasons",
  },
  "90-day-fiance": {
    tag: "90-day-fiance",
    label: "90 Day",
    fullName: "90 Day Fiance",
    keywords: [
      "90 day fiance", "90 day", "before the 90 days",
      "happily ever after", "the other way",
    ],
    color: "#F368E0",
    intro: "90 Day Fiance and its seemingly infinite universe of spinoffs follow couples navigating international relationships, K-1 visas, and the 90-day countdown to marriage. From Before the 90 Days to Happily Ever After to The Other Way, the franchise has expanded into a full cinematic universe of love, culture clash, and questionable decision-making that keeps TLC viewers glued to their screens.",
    currentSeason: null,
    airDay: null,
    network: "TLC",
    status: "between-seasons",
  },
  "selling-sunset": {
    tag: "selling-sunset",
    label: "Selling Sunset",
    fullName: "Selling Sunset",
    keywords: [
      "selling sunset", "chrishell stause", "jason oppenheim",
      "mary fitzgerald", "selling the oc",
    ],
    color: "#FF6B6B",
    intro: "Selling Sunset combines the luxury real estate market of Los Angeles with the personal drama of the agents at The Oppenheim Group. Multi-million dollar listings serve as the backdrop for office rivalries, romantic entanglements, and enough designer outfits to fill a Rodeo Drive boutique. The Netflix show has expanded into Selling the OC and Selling the City, proving that real estate drama translates across zip codes.",
    currentSeason: null,
    airDay: null,
    network: "Netflix",
    status: "between-seasons",
  },
  "married-at-first-sight": {
    tag: "married-at-first-sight",
    label: "MAFS",
    fullName: "Married at First Sight",
    keywords: ["married at first sight", "mafs"],
    color: "#DFE6E9",
    intro: "Married at First Sight takes the wildest premise in reality TV and somehow makes it work. Strangers are matched by relationship experts and literally meet for the first time at the altar. The weeks that follow are equal parts awkward, heartwarming, and completely unhinged as couples decide whether to stay married or get divorced on national television. The show airs on Lifetime and has spawned multiple international versions.",
    currentSeason: null,
    airDay: null,
    network: "Lifetime",
    status: "between-seasons",
  },
};

export const CATEGORIES: Array<{ slug: string; label: string }> = [
  { slug: "all", label: "All" },
  { slug: "reality-tv", label: "Reality TV" },
  { slug: "housewives", label: "Housewives" },
  { slug: "bravo", label: "Bravo" },
  { slug: "celebrity", label: "Celebrity" },
  { slug: "fashion", label: "Fashion" },
  { slug: "breaking", label: "Breaking" },
];

export const API_BASE_URL: string =
  process.env.NEXT_PUBLIC_API_URL || "https://dramaradar.com/api";

export const SITE_NAME = "DramaRadar";

export const SITE_DESCRIPTION =
  "Reality TV and celebrity gossip news aggregator. Always scanning for drama.";

export const SITE_URL = "https://dramaradar.com";
