#!/usr/bin/env node
// Seed script for DramaRadar cast members
// Usage: node scripts/seed-cast.js
// Then: npx wrangler kv bulk put cast-kv-entries.json --namespace-id 446b2734022b4cb8bfe094b4fc462128 --remote

const fs = require("fs");
const path = require("path");

const NOW = new Date().toISOString();

const CAST_MEMBERS = [
  // ================================================================
  // REAL HOUSEWIVES OF BEVERLY HILLS (Season 15)
  // ================================================================
  {
    slug: "kyle-richards",
    fullName: "Kyle Richards",
    displayName: "Kyle Richards",
    age: 57,
    hometown: "Hollywood, CA",
    bio: "Kyle Richards is the only original Real Housewives of Beverly Hills cast member still on the show, having appeared in every season since the 2010 premiere. The former child actress and sister of Kim and Kathy Hilton has built a career spanning decades on television. Currently navigating a separation from husband Mauricio Umansky after years of marriage, Kyle has been the emotional anchor of RHOBH through some of the franchise's most dramatic moments. She owns the lifestyle brand Kyle by Alene Too.",
    shows: ["real-housewives-beverly-hills"],
    status: "current",
    instagram: "kylerichards18",
    tiktok: "kylerichards",
    storylines: ["mauricio-separation", "kim-richards-feud", "puppygate", "original-cast"],
    coStars: ["erika-jayne", "dorit-kemsley", "sutton-stracke", "kathy-hilton"],
  },
  {
    slug: "erika-jayne",
    fullName: "Erika Girardi",
    displayName: "Erika Jayne",
    age: 54,
    hometown: "Atlanta, GA",
    bio: "Erika Jayne is a singer, actress, and Real Housewives of Beverly Hills cast member who joined the show in Season 6. Her marriage to powerhouse attorney Tom Girardi made her one of the wealthiest housewives. The fallout from Girardi's legal troubles, including allegations of stealing from his clients, became one of the most significant storylines in RHOBH history. Erika continues to perform and maintain her cabaret persona while addressing the ongoing legal aftermath.",
    shows: ["real-housewives-beverly-hills"],
    status: "current",
    instagram: "theprettymess",
    storylines: ["girardi-scandal", "pretty-mess", "expensive-everything"],
    coStars: ["kyle-richards", "dorit-kemsley", "sutton-stracke"],
  },
  {
    slug: "dorit-kemsley",
    fullName: "Dorit Kemsley",
    displayName: "Dorit Kemsley",
    age: 49,
    hometown: "Woodbridge, CT",
    bio: "Dorit Kemsley joined Real Housewives of Beverly Hills in Season 7 and quickly became known for her bold fashion choices and dramatic confrontations. Married to PK Kemsley, the couple's relationship has been a major storyline including their separation announcement. Dorit experienced a traumatic home invasion in 2021 which she discussed extensively on the show. She is the founder of Beverly Beach swimwear and Buying Beverly Hills product lines.",
    shows: ["real-housewives-beverly-hills"],
    status: "current",
    instagram: "doritkemsley",
    storylines: ["pk-separation", "home-invasion", "beverly-beach", "puppygate"],
    coStars: ["kyle-richards", "erika-jayne", "sutton-stracke"],
  },
  {
    slug: "sutton-stracke",
    fullName: "Sutton Stracke",
    displayName: "Sutton Stracke",
    age: 54,
    hometown: "Augusta, GA",
    bio: "Sutton Stracke joined Real Housewives of Beverly Hills as a friend in Season 10 before being promoted to full housewife in Season 11. The Georgia native brings southern charm and razor-sharp wit to the show. She owns Sutton Concept boutique in West Hollywood and has become a fan favorite for her honest approach and willingness to call out other cast members. Her ongoing tensions with Erika Jayne over the Girardi situation have defined her recent seasons.",
    shows: ["real-housewives-beverly-hills"],
    status: "current",
    instagram: "suttonbstracke",
    storylines: ["erika-feud", "sutton-concept", "southern-belle"],
    coStars: ["kyle-richards", "erika-jayne", "dorit-kemsley"],
  },
  {
    slug: "bozoma-saint-john",
    fullName: "Bozoma Saint John",
    displayName: "Bozoma Saint John",
    age: 48,
    hometown: "Accra, Ghana",
    bio: "Bozoma Saint John joined Real Housewives of Beverly Hills in Season 14 as one of the most accomplished women to ever join the franchise. Former Chief Marketing Officer at Netflix, Endeavor, and Uber, she brings boardroom sophistication to Beverly Hills. Currently engaged to Keely Watson, Bozoma has been navigating IVF discussions and her engagement on the show.",
    shows: ["real-housewives-beverly-hills"],
    status: "current",
    instagram: "badassboz",
    storylines: ["keely-engagement", "ivf-journey", "tech-executive"],
    coStars: ["kyle-richards", "erika-jayne", "rachel-zoe"],
  },
  {
    slug: "rachel-zoe",
    fullName: "Rachel Zoe",
    displayName: "Rachel Zoe",
    age: 54,
    hometown: "Millburn, NJ",
    bio: "Rachel Zoe is the legendary celebrity stylist turned Real Housewives of Beverly Hills cast member, joining the show in Season 15 as a newcomer. Known for styling A-list celebrities and her own Bravo show The Rachel Zoe Project, she brings fashion industry credibility to the group. Her arrival in Beverly Hills marked a significant casting move for Bravo bringing a recognized name back to the network.",
    shows: ["real-housewives-beverly-hills"],
    status: "current",
    instagram: "rachelzoe",
    storylines: ["fashion-icon", "newcomer-energy"],
    coStars: ["kyle-richards", "bozoma-saint-john", "amanda-frances"],
  },
  {
    slug: "amanda-frances",
    fullName: "Amanda Frances",
    displayName: "Amanda Frances",
    age: 39,
    hometown: "Oklahoma",
    bio: "Amanda Frances is a self-made millionaire entrepreneur and money mindset coach who joined Real Housewives of Beverly Hills in Season 15. Known for her work in the personal development and wealth building space, she brings a different kind of self-made success story to Beverly Hills. Her teachings on women and money have made her a recognizable figure in the entrepreneurial coaching world.",
    shows: ["real-housewives-beverly-hills"],
    status: "current",
    instagram: "xoamandafrances",
    storylines: ["self-made-millionaire", "money-mindset", "newcomer-energy"],
    coStars: ["rachel-zoe", "bozoma-saint-john", "kyle-richards"],
  },
  {
    slug: "kathy-hilton",
    fullName: "Kathy Hilton",
    displayName: "Kathy Hilton",
    age: 66,
    hometown: "New York, NY",
    bio: "Kathy Hilton is the mother of Paris and Nicky Hilton and sister of Kyle and Kim Richards. She joined Real Housewives of Beverly Hills as a friend in Season 11 and has remained in that capacity. Her viral Aspen meltdown is one of the most quoted moments in franchise history. She maintains her status as a friend of the cast while continuing to be a Hilton family matriarch.",
    shows: ["real-housewives-beverly-hills"],
    status: "friend-of",
    instagram: "kathyhilton",
    storylines: ["aspen-meltdown", "hilton-family", "kyle-sister"],
    coStars: ["kyle-richards", "erika-jayne", "dorit-kemsley"],
  },

  // ================================================================
  // REAL HOUSEWIVES OF ATLANTA (Season 17)
  // ================================================================
  {
    slug: "porsha-williams",
    fullName: "Porsha Williams",
    displayName: "Porsha Williams",
    age: 44,
    hometown: "Atlanta, GA",
    bio: "Porsha Williams has been a defining personality on Real Housewives of Atlanta since joining in Season 5. The granddaughter of civil rights leader Hosea Williams, she has weathered demotion, returns, marriages, divorces, and major personal transformations on screen. Following her finalized divorce from Simon Guobadia, Porsha enters Season 17 single and openly dating multiple love interests. She is the host of Bravo's Chat Room and an entrepreneur with multiple business ventures.",
    shows: ["real-housewives-atlanta"],
    status: "current",
    instagram: "porsha4real",
    storylines: ["simon-divorce", "dating-roster", "bravo-chat-room", "underground-storyline"],
    coStars: ["phaedra-parks", "drew-sidora", "k-michelle", "pinky-cole"],
  },
  {
    slug: "phaedra-parks",
    fullName: "Phaedra Parks",
    displayName: "Phaedra Parks",
    age: 52,
    hometown: "Athens, GA",
    bio: "Phaedra Parks is an attorney, mortician, and Real Housewives of Atlanta legend who originally appeared from Season 3 through Season 9. Her departure was one of the most controversial in franchise history following the Kandi Burruss rumor scandal. After successful runs on Marriage Boot Camp and The Traitors, Phaedra returned to RHOA for Season 16 in a triumphant comeback that rejuvenated the franchise. Her sharp tongue and impeccable Southern manners remain unmatched.",
    shows: ["real-housewives-atlanta"],
    status: "current",
    instagram: "phaedraparks",
    storylines: ["kandi-rumor-fallout", "comeback", "the-traitors", "attorney-mortician"],
    coStars: ["porsha-williams", "drew-sidora", "kelli-ferrell", "angela-oakley"],
  },
  {
    slug: "drew-sidora",
    fullName: "Drew Sidora",
    displayName: "Drew Sidora",
    age: 40,
    hometown: "Chicago, IL",
    bio: "Drew Sidora is an actress, singer, and Real Housewives of Atlanta cast member since Season 13. Best known for her role in The Game and her music career, Drew brought entertainment industry credibility to the franchise. Following her divorce from Ralph Pittman, she enters Season 17 navigating a new dating chapter while balancing her acting career and motherhood to her three children.",
    shows: ["real-housewives-atlanta"],
    status: "current",
    instagram: "drewsidora",
    storylines: ["ralph-divorce", "acting-career", "the-game", "dating-life"],
    coStars: ["porsha-williams", "phaedra-parks", "k-michelle"],
  },
  {
    slug: "shamea-morton-mwangi",
    fullName: "Shamea Morton Mwangi",
    displayName: "Shamea Morton",
    age: 44,
    hometown: "Atlanta, GA",
    bio: "Shamea Morton Mwangi was a longtime friend of the Real Housewives of Atlanta cast before being promoted to full housewife in Season 16. The singer, dancer, and choreographer has worked with Beyonce and other major artists. Currently launching her own rum company, she is building her entrepreneurial portfolio while navigating ongoing tensions with Porsha and clashes with Drew on Season 17.",
    shows: ["real-housewives-atlanta"],
    status: "current",
    instagram: "shamea",
    storylines: ["porsha-tension", "rum-company", "fertility-journey", "promotion"],
    coStars: ["porsha-williams", "drew-sidora", "kelli-ferrell"],
  },
  {
    slug: "angela-oakley",
    fullName: "Angela Oakley",
    displayName: "Angela Oakley",
    age: 41,
    hometown: "Atlanta, GA",
    bio: "Angela Oakley joined Real Housewives of Atlanta in Season 16 as a full housewife. Married to NBA legend Charles Oakley, she brings sports world connections to the franchise. Following the recent passing of her mother, she enters Season 17 navigating grief while continuing to build her business and repair fractured friendships from the previous season.",
    shows: ["real-housewives-atlanta"],
    status: "current",
    instagram: "angela.oakley",
    storylines: ["mother-passing", "phaedra-tension", "charles-oakley-marriage"],
    coStars: ["phaedra-parks", "porsha-williams", "kelli-ferrell"],
  },
  {
    slug: "kelli-ferrell",
    fullName: "Kelli Ferrell",
    displayName: "Kelli Ferrell",
    age: 41,
    hometown: "Atlanta, GA",
    bio: "Kelli Ferrell joined Real Housewives of Atlanta in Season 16 as the entrepreneur behind Nana's Chicken N Waffles restaurant. With her oldest daughter heading to college, Kelli navigates a new chapter of motherhood while expanding her restaurant business with a second location. She faces both heated conflicts and salacious rumors throughout Season 17.",
    shows: ["real-housewives-atlanta"],
    status: "current",
    instagram: "thekelliferrell",
    storylines: ["nanas-chicken-waffles", "porsha-conflict", "restaurant-expansion"],
    coStars: ["porsha-williams", "shamea-morton-mwangi", "angela-oakley"],
  },
  {
    slug: "pinky-cole",
    fullName: "Aisha Pinky Cole",
    displayName: "Pinky Cole",
    age: 38,
    hometown: "Baltimore, MD",
    bio: "Pinky Cole is the entrepreneur behind the Slutty Vegan empire, valued at $100 million at its peak before financial difficulties forced her to fight to buy back her own company. She joins Real Housewives of Atlanta in Season 17 as a major newcomer bringing serious business credentials and bold personality. Recently filed Chapter 11 bankruptcy for Slutty Vegan, making her storyline one of business resilience.",
    shows: ["real-housewives-atlanta"],
    status: "current",
    instagram: "pinky",
    storylines: ["slutty-vegan", "bankruptcy", "newcomer", "business-comeback"],
    coStars: ["k-michelle", "porsha-williams", "shamea-morton-mwangi"],
  },
  {
    slug: "k-michelle",
    fullName: "Kimberly Michelle Pate",
    displayName: "K. Michelle",
    age: 43,
    hometown: "Memphis, TN",
    bio: "K. Michelle is a Grammy-nominated R&B singer-songwriter and former Love & Hip Hop star who joins Real Housewives of Atlanta as a Season 17 newcomer. Known for her unfiltered personality and Billboard charting career, she is currently pursuing country music as a new chapter while navigating a recent marriage. Her arrival in the Bravoverse has already produced fireworks, with Drew Sidora unfollowing her before the season even aired.",
    shows: ["real-housewives-atlanta"],
    status: "current",
    instagram: "kmichelle",
    storylines: ["love-hip-hop", "country-music", "newcomer", "drew-feud"],
    coStars: ["pinky-cole", "porsha-williams", "drew-sidora"],
  },
  {
    slug: "cynthia-bailey",
    fullName: "Cynthia Bailey",
    displayName: "Cynthia Bailey",
    age: 58,
    hometown: "Tuskegee, AL",
    bio: "Cynthia Bailey is a Real Housewives of Atlanta legend who appeared as a main housewife from Season 3 through Season 13. The former Wilhelmina model has remained connected to the franchise as a friend of the cast in subsequent seasons. Returns for Season 17 as a friend, providing a steady, calming force amid the drama. She owns Cynthia Bailey Eyewear and remains one of the most beloved housewives in franchise history.",
    shows: ["real-housewives-atlanta"],
    status: "friend-of",
    instagram: "cynthiabailey",
    storylines: ["the-bailey-bowl", "model-career", "franchise-legend"],
    coStars: ["porsha-williams", "phaedra-parks", "drew-sidora"],
  },

  // ================================================================
  // REAL HOUSEWIVES OF POTOMAC (Season 11)
  // ================================================================
  {
    slug: "karen-huger",
    fullName: "Karen Huger",
    displayName: "Karen Huger",
    age: 62,
    hometown: "Surry County, VA",
    bio: "Karen Huger is the self-proclaimed Grande Dame of Potomac and one of the original Real Housewives of Potomac cast members. After a guilty conviction for DUI in 2024, she served six months in prison before being released early in September 2025. Returns to RHOP for Season 11 in a triumphant comeback after her legal troubles. Her ongoing rivalry with Gizelle Bryant remains one of the franchise's most entertaining feuds.",
    shows: ["real-housewives-potomac"],
    status: "current",
    instagram: "thekarenhuger",
    storylines: ["dui-prison", "grande-dame", "gizelle-feud", "original-cast"],
    coStars: ["gizelle-bryant", "robyn-dixon", "ashley-darby"],
  },
  {
    slug: "gizelle-bryant",
    fullName: "Gizelle Bryant",
    displayName: "Gizelle Bryant",
    age: 55,
    hometown: "Houston, TX",
    bio: "Gizelle Bryant is an original Real Housewives of Potomac cast member who has appeared in every season since the show premiered in 2016. The mother of three daughters and ex-wife of Pastor Jamal Bryant, she founded the EveryHue Beauty cosmetics line. Her on-and-off again rivalry with Karen Huger has produced some of the franchise's most quoted moments. Known for her signature green eyes and razor sharp commentary.",
    shows: ["real-housewives-potomac"],
    status: "current",
    instagram: "therealgizellebryant",
    storylines: ["green-eyed-bandit", "karen-feud", "everyhue-beauty", "pastor-jamal"],
    coStars: ["karen-huger", "robyn-dixon", "ashley-darby"],
  },
  {
    slug: "robyn-dixon",
    fullName: "Robyn Dixon",
    displayName: "Robyn Dixon",
    age: 46,
    hometown: "Baltimore, MD",
    bio: "Robyn Dixon is an original Real Housewives of Potomac cast member who appeared from Season 1 through Season 8 before being fired from the show. Returns to RHOP for Season 11 as a friend of the cast after her two-season absence. Her relationship and remarriage to Juan Dixon has been a long-running storyline. Co-hosts the popular Reasonably Shady podcast with Gizelle Bryant.",
    shows: ["real-housewives-potomac"],
    status: "friend-of",
    instagram: "robyndixon10",
    storylines: ["fired-rehired", "juan-dixon-marriage", "reasonably-shady"],
    coStars: ["gizelle-bryant", "karen-huger", "ashley-darby"],
  },
  {
    slug: "ashley-darby",
    fullName: "Ashley Darby",
    displayName: "Ashley Darby",
    age: 37,
    hometown: "Bowie, MD",
    bio: "Ashley Darby joined Real Housewives of Potomac in Season 2 and has been a constant presence on the show. The former Miss District of Columbia and her relationship with the late Michael Darby provided years of storyline material. Following his passing, she has navigated single motherhood to her two sons while continuing on the show.",
    shows: ["real-housewives-potomac"],
    status: "current",
    instagram: "ashleyboalch",
    storylines: ["michael-darby", "single-motherhood", "miss-dc"],
    coStars: ["gizelle-bryant", "wendy-osefo", "stacey-rusch"],
  },
  {
    slug: "wendy-osefo",
    fullName: "Wendy Osefo",
    displayName: "Wendy Osefo",
    age: 41,
    hometown: "Maryland",
    bio: "Wendy Osefo joined Real Housewives of Potomac in Season 5 with multiple advanced degrees and a career as a political commentator. Known as Dr. Wendy on the show, she brings academic credentials to the franchise. In October 2025, she and her husband were arrested in Maryland on multiple counts of fraud related to allegations of falsely reporting a burglary. The legal situation continues to develop as a major Season 11 storyline.",
    shows: ["real-housewives-potomac"],
    status: "current",
    instagram: "wendyosefo",
    storylines: ["fraud-arrest", "dr-wendy", "political-commentator"],
    coStars: ["gizelle-bryant", "ashley-darby", "stacey-rusch"],
  },
  {
    slug: "stacey-rusch",
    fullName: "Stacey Rusch",
    displayName: "Stacey Rusch",
    age: 49,
    hometown: "Washington DC",
    bio: "Stacey Rusch joined Real Housewives of Potomac in Season 9 and has quickly become a polarizing figure on the show. The Washington DC socialite brings high-society credentials to the franchise. Returns for Season 11 as a full housewife after surviving the Season 10 cast shakeup.",
    shows: ["real-housewives-potomac"],
    status: "current",
    instagram: "staceyrusch",
    storylines: ["dc-socialite", "season-9-newcomer"],
    coStars: ["gizelle-bryant", "ashley-darby", "wendy-osefo"],
  },
  {
    slug: "tia-glover",
    fullName: "Tia Glover",
    displayName: "Tia Glover",
    age: 39,
    hometown: "Maryland",
    bio: "Tia Glover joined Real Housewives of Potomac in Season 10 as a new cast member. Returns for Season 11 as a full housewife. The Maryland local brings fresh energy to the franchise.",
    shows: ["real-housewives-potomac"],
    status: "current",
    instagram: "tiamariaglover",
    storylines: ["season-10-newcomer"],
    coStars: ["gizelle-bryant", "ashley-darby", "wendy-osefo"],
  },

  // ================================================================
  // REAL HOUSEWIVES OF NEW JERSEY (Between Seasons)
  // ================================================================
  {
    slug: "teresa-giudice",
    fullName: "Teresa Giudice",
    displayName: "Teresa Giudice",
    age: 53,
    hometown: "Paterson, NJ",
    bio: "Teresa Giudice is the only original Real Housewives of New Jersey cast member still on the show, having appeared in every season since 2009. Famous for the legendary Season 1 table flip that became a cultural moment, Teresa has weathered prison time, deportation threats against ex-husband Joe Giudice, a bitter divorce, and an explosive remarriage to Luis Ruelas. Her ongoing feud with brother Joe Gorga and sister-in-law Melissa Gorga has defined recent seasons of the franchise.",
    shows: ["real-housewives-new-jersey"],
    status: "current",
    instagram: "teresagiudice",
    storylines: ["table-flip", "prison-stint", "gorga-feud", "luis-ruelas-marriage"],
    coStars: ["melissa-gorga", "dolores-catania", "margaret-josephs"],
  },
  {
    slug: "melissa-gorga",
    fullName: "Melissa Gorga",
    displayName: "Melissa Gorga",
    age: 46,
    hometown: "Toms River, NJ",
    bio: "Melissa Gorga joined Real Housewives of New Jersey in Season 3 and has appeared in every season since. Married to Joe Gorga, brother of Teresa Giudice, the family dynamics have been the central drama of RHONJ for over a decade. The complete breakdown of her relationship with Teresa has left the cast permanently fractured. She owns Envy boutique and is set to return for the next season.",
    shows: ["real-housewives-new-jersey"],
    status: "current",
    instagram: "melissagorga",
    storylines: ["teresa-feud", "joe-gorga-marriage", "envy-boutique"],
    coStars: ["teresa-giudice", "dolores-catania", "jennifer-aydin"],
  },
  {
    slug: "dolores-catania",
    fullName: "Dolores Catania",
    displayName: "Dolores Catania",
    age: 54,
    hometown: "Paterson, NJ",
    bio: "Dolores Catania joined Real Housewives of New Jersey in Season 7 and has been a consistent voice of reason in the increasingly fractured cast. Known for her loyalty to Teresa Giudice and her willingness to call out drama directly, Dolores brings Jersey toughness and genuine friendships to the show. Currently appears as a friend on Real Housewives of Rhode Island Season 1.",
    shows: ["real-housewives-new-jersey", "real-housewives-rhode-island"],
    status: "current",
    instagram: "dolorescatania",
    storylines: ["teresa-loyalty", "rhori-friend", "jersey-tough"],
    coStars: ["teresa-giudice", "melissa-gorga", "jennifer-aydin"],
  },
  {
    slug: "margaret-josephs",
    fullName: "Margaret Josephs",
    displayName: "Margaret Josephs",
    age: 58,
    hometown: "New York, NY",
    bio: "Margaret Josephs joined Real Housewives of New Jersey in Season 8 and quickly became known for her colorful personality, signature pigtails, and willingness to instigate drama. Founder of the Macbeth Collection lifestyle brand, she has been at the center of multiple major storylines including her ongoing tensions with Jennifer Aydin. Recently announced her departure from RHONJ.",
    shows: ["real-housewives-new-jersey"],
    status: "former",
    instagram: "themargaretjosephs",
    storylines: ["macbeth-collection", "departure", "jennifer-feud"],
    coStars: ["teresa-giudice", "melissa-gorga", "jennifer-aydin"],
  },
  {
    slug: "jennifer-aydin",
    fullName: "Jennifer Aydin",
    displayName: "Jennifer Aydin",
    age: 48,
    hometown: "Paramus, NJ",
    bio: "Jennifer Aydin joined Real Housewives of New Jersey in Season 9 and has built a reputation for being unfiltered and dramatic. Married to Dr. Bill Aydin, the couple's marital troubles have been a recurring storyline. Known for her opulent lifestyle and confrontational style, she has been at the center of countless cast disputes.",
    shows: ["real-housewives-new-jersey"],
    status: "current",
    instagram: "jenniferaydin",
    storylines: ["bill-marriage-troubles", "margaret-feud", "opulent-lifestyle"],
    coStars: ["teresa-giudice", "melissa-gorga", "dolores-catania"],
  },

  // ================================================================
  // REAL HOUSEWIVES OF SALT LAKE CITY (Season 5/6)
  // ================================================================
  {
    slug: "lisa-barlow",
    fullName: "Lisa Barlow",
    displayName: "Lisa Barlow",
    age: 50,
    hometown: "Brooklyn, NY",
    bio: "Lisa Barlow joined Real Housewives of Salt Lake City as an original cast member in Season 1. The successful entrepreneur owns Vida Tequila and Luxe Marketing among other ventures. Known for her business acumen, fierce loyalty, and viral Gucci moments, she has become one of the most quotable housewives in the franchise.",
    shows: ["real-housewives-salt-lake-city"],
    status: "current",
    instagram: "lisabarlow14",
    storylines: ["vida-tequila", "fucking-gucci", "original-cast"],
    coStars: ["meredith-marks", "heather-gay", "whitney-rose"],
  },
  {
    slug: "meredith-marks",
    fullName: "Meredith Marks",
    displayName: "Meredith Marks",
    age: 53,
    hometown: "Chicago, IL",
    bio: "Meredith Marks joined Real Housewives of Salt Lake City as an original cast member in Season 1. The jewelry designer owns Meredith Marks jewelry boutiques and brings a more reserved, calculated presence to the show. Her marriage to Seth Marks and the complicated dynamics around it have been ongoing storylines.",
    shows: ["real-housewives-salt-lake-city"],
    status: "current",
    instagram: "meredithmarks",
    storylines: ["seth-marriage", "jewelry-empire", "original-cast", "engaging-disengaging"],
    coStars: ["lisa-barlow", "heather-gay", "whitney-rose"],
  },
  {
    slug: "heather-gay",
    fullName: "Heather Gay",
    displayName: "Heather Gay",
    age: 51,
    hometown: "Salt Lake City, UT",
    bio: "Heather Gay joined Real Housewives of Salt Lake City as an original cast member in Season 1. The owner of Beauty Lab and Laser medspa is a former Mormon who provides crucial cultural context for the show's exploration of LDS dynamics. Author of the New York Times bestseller Bad Mormon, she became famous for the iconic Black Eye season finale moment.",
    shows: ["real-housewives-salt-lake-city"],
    status: "current",
    instagram: "heathergay29",
    storylines: ["bad-mormon-book", "black-eye", "beauty-lab", "lds-context"],
    coStars: ["lisa-barlow", "meredith-marks", "whitney-rose"],
  },
  {
    slug: "whitney-rose",
    fullName: "Whitney Rose",
    displayName: "Whitney Rose",
    age: 50,
    hometown: "Salt Lake City, UT",
    bio: "Whitney Rose joined Real Housewives of Salt Lake City as an original cast member in Season 1. The Wild Rose Beauty founder and former Mormon brings family drama and her relationship with husband Justin Rose to the show. Known for her honest approach to discussing her family's struggles with addiction.",
    shows: ["real-housewives-salt-lake-city"],
    status: "current",
    instagram: "whitneywildrose",
    storylines: ["wild-rose-beauty", "family-addiction", "justin-marriage"],
    coStars: ["lisa-barlow", "meredith-marks", "heather-gay"],
  },
  {
    slug: "mary-cosby",
    fullName: "Mary Cosby",
    displayName: "Mary Cosby",
    age: 53,
    hometown: "Berkeley, CA",
    bio: "Mary Cosby is one of the most controversial Real Housewives of Salt Lake City cast members, returning after multiple seasons away. The pastor of Faith Temple Pentecostal Church is married to her grandmother's husband, a unique situation that has been central to her storyline. Recently dealing with the death of her son Robert Cosby Jr., which Andy Cohen addressed publicly.",
    shows: ["real-housewives-salt-lake-city"],
    status: "current",
    instagram: "marymcosby",
    storylines: ["pastor-controversy", "son-death", "smells-like-hospital"],
    coStars: ["lisa-barlow", "meredith-marks", "heather-gay"],
  },

  // ================================================================
  // REAL HOUSEWIVES OF MIAMI (Season 7)
  // ================================================================
  {
    slug: "larsa-pippen",
    fullName: "Larsa Pippen",
    displayName: "Larsa Pippen",
    age: 51,
    hometown: "Chicago, IL",
    bio: "Larsa Pippen is the ex-wife of NBA legend Scottie Pippen and longtime friend of the Kardashian family. She joined Real Housewives of Miami in Season 1 of the original run and returned when the show was revived on Peacock. Her relationship with Marcus Jordan, son of Michael Jordan, became one of the most discussed reality TV relationships of recent years.",
    shows: ["real-housewives-miami"],
    status: "current",
    instagram: "larsapippen",
    storylines: ["marcus-jordan-relationship", "scottie-pippen-ex", "kardashian-friendship"],
    coStars: ["alexia-nepola", "lisa-hochstein", "guerdy-abraira"],
  },
  {
    slug: "alexia-nepola",
    fullName: "Alexia Echevarria Nepola",
    displayName: "Alexia Nepola",
    age: 58,
    hometown: "Havana, Cuba",
    bio: "Alexia Nepola is an original Real Housewives of Miami cast member from the show's first run. The former magazine editor and Cuban-American socialite has been navigating her relationship with Todd Nepola through marriage and divorce on screen. Her family dynamics including her sons Peter and Frankie have been ongoing storylines.",
    shows: ["real-housewives-miami"],
    status: "current",
    instagram: "alexianepola",
    storylines: ["todd-divorce", "cuban-american", "original-cast"],
    coStars: ["larsa-pippen", "lisa-hochstein", "guerdy-abraira"],
  },
  {
    slug: "lisa-hochstein",
    fullName: "Lisa Hochstein",
    displayName: "Lisa Hochstein",
    age: 43,
    hometown: "Toronto, Canada",
    bio: "Lisa Hochstein joined Real Housewives of Miami in the original run as the Boobie Queen. Her divorce from plastic surgeon Lenny Hochstein became a major storyline, with their custody battle and his new relationship dominating headlines. She continues to navigate single motherhood while building her own brand.",
    shows: ["real-housewives-miami"],
    status: "current",
    instagram: "lisahochstein",
    storylines: ["lenny-divorce", "boobie-queen", "custody-battle"],
    coStars: ["larsa-pippen", "alexia-nepola", "guerdy-abraira"],
  },
  {
    slug: "guerdy-abraira",
    fullName: "Guerdy Abraira",
    displayName: "Guerdy Abraira",
    age: 47,
    hometown: "Haiti",
    bio: "Guerdy Abraira joined Real Housewives of Miami when the show was revived. The Haitian-born luxury wedding planner has organized events for celebrities and brings high-end industry credentials to the show. Her openness about her breast cancer diagnosis and treatment provided some of the most moving storylines in recent reality TV.",
    shows: ["real-housewives-miami"],
    status: "current",
    instagram: "guerdydesigns",
    storylines: ["breast-cancer-journey", "wedding-planner", "haitian-american"],
    coStars: ["larsa-pippen", "alexia-nepola", "lisa-hochstein"],
  },

  // ================================================================
  // REAL HOUSEWIVES OF DUBAI (Season 2)
  // ================================================================
  {
    slug: "caroline-stanbury",
    fullName: "Caroline Stanbury",
    displayName: "Caroline Stanbury",
    age: 49,
    hometown: "London, UK",
    bio: "Caroline Stanbury is a Real Housewives of Dubai cast member and previous star of Ladies of London. The British socialite married former footballer Sergio Carrallo and the couple's age gap relationship has been a central storyline. Known for her sharp tongue and Ladies of London era drama, she brought franchise crossover credibility to Dubai.",
    shows: ["real-housewives-dubai", "ladies-of-london"],
    status: "current",
    instagram: "carolinestanbury",
    storylines: ["sergio-marriage", "ladies-of-london", "british-socialite"],
    coStars: ["chanel-ayan", "caroline-brooks", "lesa-milan"],
  },
  {
    slug: "chanel-ayan",
    fullName: "Chanel Ayan",
    displayName: "Chanel Ayan",
    age: 47,
    hometown: "Wajir, Kenya",
    bio: "Chanel Ayan is a Real Housewives of Dubai cast member and the first Black model from East Africa to walk for major fashion houses. The Kenyan-born model brings fashion industry credentials and unfiltered personality to the franchise. Her storylines have included family dynamics and career evolution.",
    shows: ["real-housewives-dubai"],
    status: "current",
    instagram: "chanelayan",
    storylines: ["modeling-career", "east-african-icon"],
    coStars: ["caroline-stanbury", "caroline-brooks", "lesa-milan"],
  },

  // ================================================================
  // REAL HOUSEWIVES OF NEW YORK (Season 15, reboot cast)
  // ================================================================
  {
    slug: "sai-de-silva",
    fullName: "Sai De Silva",
    displayName: "Sai De Silva",
    age: 46,
    hometown: "New York, NY",
    bio: "Sai De Silva is part of the rebooted Real Housewives of New York City cast that debuted in Season 14. The lifestyle influencer and content creator brings social media savvy to the franchise. Her marriage and family dynamics with husband Daniel and their two children provide ongoing storylines.",
    shows: ["real-housewives-new-york"],
    status: "current",
    instagram: "scoutthecity",
    storylines: ["lifestyle-influencer", "rhony-reboot", "daniel-marriage"],
    coStars: ["ubah-hassan", "brynn-whitfield", "erin-lichy"],
  },
  {
    slug: "ubah-hassan",
    fullName: "Ubah Hassan",
    displayName: "Ubah Hassan",
    age: 41,
    hometown: "Mogadishu, Somalia",
    bio: "Ubah Hassan is a Real Housewives of New York City cast member from the rebooted Season 14. The Somali-Canadian model and entrepreneur founded the UBAH HOT hot sauce brand. As a survivor of sexual violence, her on-screen disputes with castmate Brynn Whitfield over related comments raised important conversations about how reality TV handles sensitive topics.",
    shows: ["real-housewives-new-york"],
    status: "current",
    instagram: "ubah",
    storylines: ["ubah-hot-sauce", "brynn-conflict", "somali-immigrant"],
    coStars: ["sai-de-silva", "brynn-whitfield", "jenna-lyons"],
  },
  {
    slug: "brynn-whitfield",
    fullName: "Brynn Whitfield",
    displayName: "Brynn Whitfield",
    age: 38,
    hometown: "Indiana",
    bio: "Brynn Whitfield is part of the rebooted Real Housewives of New York City cast. The brand and communications strategist brought her single dating life in NYC to the show. Her ongoing tensions with Ubah Hassan and other cast members have made her one of the more polarizing figures in the reboot era.",
    shows: ["real-housewives-new-york"],
    status: "current",
    instagram: "brynnwhitfield",
    storylines: ["nyc-dating-life", "ubah-feud", "rhony-reboot"],
    coStars: ["sai-de-silva", "ubah-hassan", "jenna-lyons"],
  },
  {
    slug: "jenna-lyons",
    fullName: "Jenna Lyons",
    displayName: "Jenna Lyons",
    age: 57,
    hometown: "Boston, MA",
    bio: "Jenna Lyons is a fashion icon and former J.Crew President and Creative Director who joined the rebooted Real Housewives of New York City. Bringing serious fashion industry credentials to the franchise, she founded LoveSeen, a luxury false eyelash brand. Her style and commentary made her an instant standout in the new cast.",
    shows: ["real-housewives-new-york"],
    status: "current",
    instagram: "jennalyonsnyc",
    storylines: ["jcrew-creative-director", "loveseen", "fashion-icon"],
    coStars: ["sai-de-silva", "ubah-hassan", "erin-lichy"],
  },
  {
    slug: "erin-lichy",
    fullName: "Erin Dana Lichy",
    displayName: "Erin Lichy",
    age: 38,
    hometown: "Brooklyn, NY",
    bio: "Erin Lichy is part of the rebooted Real Housewives of New York City cast. The Tribeca-based real estate broker and interior designer founded Homegirl, an interior design firm. Her Orthodox Jewish background brings cultural perspective to the show, and her family with husband Abe and their three children provides regular storylines.",
    shows: ["real-housewives-new-york"],
    status: "current",
    instagram: "erinlichy",
    storylines: ["homegirl-interiors", "tribeca-real-estate", "rhony-reboot"],
    coStars: ["sai-de-silva", "jenna-lyons", "jessel-taank"],
  },
  {
    slug: "jessel-taank",
    fullName: "Jessel Taank",
    displayName: "Jessel Taank",
    age: 43,
    hometown: "London, UK",
    bio: "Jessel Taank is part of the rebooted Real Housewives of New York City cast. The British-born fashion publicist brings international flair and her Indian heritage to the franchise. Married to Pavit Randhawa, the couple's IVF journey to have their twin sons was a featured storyline.",
    shows: ["real-housewives-new-york"],
    status: "current",
    instagram: "jesseltaank",
    storylines: ["ivf-twins", "fashion-pr", "indian-british-american"],
    coStars: ["erin-lichy", "sai-de-silva", "brynn-whitfield"],
  },

  // ================================================================
  // REAL HOUSEWIVES OF RHODE ISLAND (Season 1)
  // ================================================================
  {
    slug: "ashley-iaconetti",
    fullName: "Ashley Iaconetti",
    displayName: "Ashley Iaconetti",
    age: 38,
    hometown: "Great Falls, VA",
    bio: "Ashley Iaconetti is a Bachelor Nation alum who appeared on The Bachelor and Bachelor in Paradise before becoming a cast member on the inaugural season of Real Housewives of Rhode Island. Married to fellow Bachelor alum Jared Haibon, the couple resides in Rhode Island. She brings reality TV crossover appeal to the new franchise.",
    shows: ["real-housewives-rhode-island", "bachelor-bachelorette"],
    status: "current",
    instagram: "ashley_iaconetti",
    storylines: ["bachelor-nation", "jared-haibon-marriage", "rhori-original"],
    coStars: ["jo-ellen-tiberi", "rosie-dimare", "alicia-carmody"],
  },
  {
    slug: "jo-ellen-tiberi",
    fullName: "Jo-Ellen Tiberi",
    displayName: "Jo-Ellen Tiberi",
    age: 51,
    hometown: "Rhode Island",
    bio: "Jo-Ellen Tiberi is part of the inaugural Real Housewives of Rhode Island Season 1 cast. The Italian-American Rhode Island native is already at the center of major drama in the new franchise, including a confrontation with Rulla's husband Brian over alleged interference at her workplace.",
    shows: ["real-housewives-rhode-island"],
    status: "current",
    instagram: "joellentiberi",
    storylines: ["rulla-brian-feud", "rhori-original", "italian-american"],
    coStars: ["ashley-iaconetti", "rosie-dimare", "rulla-nehme"],
  },
  {
    slug: "rosie-dimare",
    fullName: "Rosie DiMare",
    displayName: "Rosie DiMare",
    age: 42,
    hometown: "Rhode Island",
    bio: "Rosie DiMare is a Real Housewives of Rhode Island Season 1 cast member. The Rhode Island native has been at the center of love life rumors throughout the inaugural season, with the cast actively dissecting her relationship status.",
    shows: ["real-housewives-rhode-island"],
    status: "current",
    instagram: "rosiedimare",
    storylines: ["love-life-rumors", "rhori-original"],
    coStars: ["ashley-iaconetti", "jo-ellen-tiberi", "kelsey-swanson"],
  },
  {
    slug: "kelsey-swanson",
    fullName: "Kelsey Swanson",
    displayName: "Kelsey Swanson",
    age: 40,
    hometown: "Rhode Island",
    bio: "Kelsey Swanson is part of the inaugural Real Housewives of Rhode Island Season 1 cast. She has been featured in After Show segments unpacking the explosive drama with castmates Rosie DiMare and Jo-Ellen Tiberi.",
    shows: ["real-housewives-rhode-island"],
    status: "current",
    instagram: "kelseyswanson",
    storylines: ["rhori-original"],
    coStars: ["ashley-iaconetti", "rosie-dimare", "jo-ellen-tiberi"],
  },
  {
    slug: "alicia-carmody",
    fullName: "Alicia Carmody",
    displayName: "Alicia Carmody",
    age: 41,
    hometown: "Rhode Island",
    bio: "Alicia Carmody is a Real Housewives of Rhode Island Season 1 cast member. She has been featured prominently throughout the inaugural season including dinner gatherings where the aunties pile on Italian food and pressure her about marriage timeline.",
    shows: ["real-housewives-rhode-island"],
    status: "current",
    instagram: "aliciacarmody",
    storylines: ["rhori-original", "marriage-pressure"],
    coStars: ["ashley-iaconetti", "rosie-dimare", "rulla-nehme"],
  },
  {
    slug: "rulla-nehme",
    fullName: "Rulla Nehme Pontarelli",
    displayName: "Rulla Nehme",
    age: 44,
    hometown: "Rhode Island",
    bio: "Rulla Nehme Pontarelli is a Real Housewives of Rhode Island Season 1 cast member. Her husband Brian's interference with castmate Jo-Ellen Tiberi's workplace became a major Season 1 storyline.",
    shows: ["real-housewives-rhode-island"],
    status: "current",
    instagram: "rullanehme",
    storylines: ["brian-jo-ellen-feud", "rhori-original"],
    coStars: ["jo-ellen-tiberi", "ashley-iaconetti", "elizabeth-mcgraw"],
  },
  {
    slug: "elizabeth-mcgraw",
    fullName: "Elizabeth McGraw",
    displayName: "Liz McGraw",
    age: 39,
    hometown: "Rhode Island",
    bio: "Elizabeth McGraw is part of the inaugural Real Housewives of Rhode Island Season 1 cast.",
    shows: ["real-housewives-rhode-island"],
    status: "current",
    instagram: "lizmcgraw",
    storylines: ["rhori-original"],
    coStars: ["ashley-iaconetti", "rosie-dimare", "alicia-carmody"],
  },
];

// Generate KV bulk put entries
function generateKvEntries() {
  const entries = [];

  // Build the cast index
  const indexSlugs = CAST_MEMBERS.map((m) => m.slug);

  // Add the index entry
  entries.push({
    key: "cast:index",
    value: JSON.stringify(indexSlugs),
  });

  // Add each cast member
  for (const member of CAST_MEMBERS) {
    const fullMember = {
      ...member,
      createdAt: NOW,
      updatedAt: NOW,
    };

    entries.push({
      key: `cast:${member.slug}`,
      value: JSON.stringify(fullMember),
    });
  }

  return entries;
}

const entries = generateKvEntries();

// Write the bulk put JSON file
const outputPath = path.join(__dirname, "..", "cast-kv-entries.json");
fs.writeFileSync(outputPath, JSON.stringify(entries, null, 2));

console.log(`Generated ${entries.length} KV entries (1 index + ${CAST_MEMBERS.length} cast members)`);
console.log(`Output: ${outputPath}`);
console.log("");
console.log("To insert into KV, run:");
console.log(`npx wrangler kv bulk put cast-kv-entries.json --namespace-id 446b2734022b4cb8bfe094b4fc462128 --remote`);
